### ISSUE TITLE
Failing TestSecondaryServices.test_update_service_service_succeeds

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-aggregator#111]
`TestSecondaryServices.test_update_service_service_succeeds` starts failing:

```
=================================== FAILURES ===================================
__________ TestSecondaryServices.test_update_service_service_succeeds __________

self = <tests.test_views.TestSecondaryServices object at 0x7f24c2a77a60>
api100 = <openeo_driver.testing.ApiTester object at 0x7f24c2277100>
backend1 = 'https://b1.test/v1'
requests_mock = <requests_mock.mocker.Mocker object at 0x7f24c21aa640>
service_metadata_wmts_foo = ServiceMetadata(id='wmts-foo', url='https://oeo.net/wmts/foo', type='WMTS', process={'process_graph': {'foo': {'proces...on={'version': '0.5.8'}, title='Test WMTS service', description=None, created=None, plan=None, costs=None, budget=None)

    def test_update_service_service_succeeds(
        self, api100, backend1, requests_mock, service_metadata_wmts_foo
    ):
        """When it receives an existing service ID and a correct payload, it updates the expected service."""
    
        api100.set_auth_bearer_token(TEST_USER_BEARER_TOKEN)
    
        mock_patch = requests_mock.patch(
            backend1 + "/services/wmts-foo",
            json=service_metadata_wmts_foo.prepare_for_json(),
            status_code=204
        )
        process_graph = {"bar": {"process_id": "bar", "arguments": {"new_arg": "somevalue"}}}
        json_payload = {"process": {"process_graph": process_graph}}
    
        resp = api100.patch("/services/b1-wmts-foo", json=json_payload)
    
>       assert resp.status_code == 204
E       assert 500 == 204
E        +  where 500 = <openeo_driver.testing.ApiResponse object at 0x7f24c1e0cf10>.status_code

tests/test_views.py:2301: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  openeo_aggregator.backend:backend.py:1105 Failed to update service 'wmts-foo' from 'b1': ChunkedEncodingError(ProtocolError('Connection broken: IncompleteRead(335 bytes read, -335 more expected)', IncompleteRead(335 bytes read, -335 more expected)))
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 705, in _error_catcher
    yield
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 830, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(335 bytes read, -335 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 935, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 906, in read
    data = self._raw_read(amt)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 830, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 722, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(335 bytes read, -335 more expected)', IncompleteRead(335 bytes read, -335 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/src/openeo_aggregator/backend.py", line 1097, in update_service
    con.patch(f"/services/{backend_service_id}", json=json, expected_status=204)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo/rest/connection.py", line 195, in patch
    return self.request("patch", path=path, allow_redirects=False, **kwargs)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo/rest/connection.py", line 614, in request
    return _request()
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo/rest/connection.py", line 607, in _request
    return super(Connection, self).request(
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo/rest/connection.py", line 106, in request
    resp = self.session.request(
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests_mock/mocker.py", line 185, in _fake_send
    return _original_send(session, request, **kwargs)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(335 bytes read, -335 more expected)', IncompleteRead(335 bytes read, -335 more expected))
ERROR    openeo_driver.views.error:views.py:267 OpenEOApiException(status_code=500, code='Internal', message="Failed to update service 'wmts-foo' from 'b1': ChunkedEncodingError(ProtocolError('Connection broken: IncompleteRead(335 bytes read, -335 more expected)', IncompleteRead(335 bytes read, -335 more expected)))", id='r-d13f7c566114405d938a90c31f157f6c')
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 705, in _error_catcher
    yield
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 830, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(335 bytes read, -335 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 935, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 906, in read
    data = self._raw_read(amt)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 830, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/urllib3/response.py", line 722, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(335 bytes read, -335 more expected)', IncompleteRead(335 bytes read, -335 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/src/openeo_aggregator/backend.py", line 1097, in update_service
    con.patch(f"/services/{backend_service_id}", json=json, expected_status=204)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo/rest/connection.py", line 195, in patch
    return self.request("patch", path=path, allow_redirects=False, **kwargs)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo/rest/connection.py", line 614, in request
    return _request()
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo/rest/connection.py", line 607, in _request
    return super(Connection, self).request(
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo/rest/connection.py", line 106, in request
    resp = self.session.request(
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests_mock/mocker.py", line 185, in _fake_send
    return _original_send(session, request, **kwargs)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(335 bytes read, -335 more expected)', IncompleteRead(335 bytes read, -335 more expected))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo_driver/users/auth.py", line 88, in decorated
    return f(*args, **kwargs)
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/venv38/lib64/python3.8/site-packages/openeo_driver/views.py", line 1420, in service_patch
    backend_implementation.secondary_services.update_service(user_id=user.user_id, service_id=service_id,
  File "/var/lib/jenkins/workspace/openEO_openeo-aggregator_master/src/openeo_aggregator/backend.py", line 1106, in update_service
    raise OpenEOApiException(
openeo_driver.errors.OpenEOApiException: Failed to update service 'wmts-foo' from 'b1': ChunkedEncodingError(ProtocolError('Connection broken: IncompleteRead(335 bytes read, -335 more expected)', IncompleteRead(335 bytes read, -335 more expected)))
```

Couldn't reproduce locally until upgrading `urllib3` to latest 2.0.2 (was 1.26.12 before for me)

**Comment by soxofaan** [comment]
the test apparently mocked a PATCH request with a 204 status code and a non-empty body, which is invalid and updated urllib3 started chocking on that
